#!/bin/bash
# Quick start guide for Flight Price Finder

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🛫 Flight Price Finder v2.0 - QUICK START GUIDE       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo ""
echo "📌 CAMBIOS PRINCIPALES DESDE v1.0"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  v1.0 (Telegram Bot)          →    v2.0 (Web App)"
echo "  ────────────────────              ─────────────"
echo "  • Solo Telegram              →    • Web + Telegram (opcional)"
echo "  • 1 fuente (Skyscanner)      →    • 2+ fuentes (Skyscanner, Kayak)"
echo "  • 6 rutas fijas              →    • 20+ rutas configurables"
echo "  • Alertas por chat           →    • Dashboard interactivo"
echo "  • Sin interfaz visual        →    • UI responsiva moderna"
echo "  • Servidor remoto            →    • Servidor local + BD local"
echo ""
echo ""
echo "🚀 INICIO RÁPIDO (3 pasos)"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  1️⃣  Instalar dependencias:"
echo "      $ npm install"
echo ""
echo "  2️⃣  Iniciar servidor:"
echo "      $ npm start"
echo ""
echo "  3️⃣  Abrir navegador:"
echo "      http://localhost:3000"
echo ""
echo ""
echo "🔍 ARCHIVOS IMPORTANTES"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  server/app.js               - Servidor Express"
echo "  public/index.html           - Interfaz web"
echo "  server/scrapers/            - Web scrapers (Skyscanner, Kayak)"
echo "  server/database/db.js       - Base de datos SQLite"
echo "  package.json                - Dependencias del proyecto"
echo ""
echo ""
echo "📚 DOCUMENTACIÓN"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  README.md              - Guía completa"
echo "  INSTALL.md             - Instrucciones instalación"
echo "  ARCHITECTURE.md        - Diseño técnico"
echo "  PROJECT_SUMMARY.md     - Este documento"
echo "  CHANGELOG.md           - Historial de versiones"
echo ""
echo ""
echo "🧪 TESTING"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  $ npm test             - Ejecutar todos los tests"
echo "  $ npm run demo         - Demo con ejemplos"
echo "  $ npm run test:scraper - Tests de scrapers"
echo "  $ npm run test:api     - Tests de API"
echo "  $ npm run test:db      - Tests de base de datos"
echo ""
echo ""
echo "🌐 RUTAS DISPONIBLES"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  Búsqueda:"
echo "    GET  /api/search?origin=MAD&destination=AEP"
echo ""
echo "  Alertas:"
echo "    POST   /api/alert"
echo "    GET    /api/alerts"
echo "    DELETE /api/alert/:id"
echo ""
echo "  Historial:"
echo "    GET  /api/history/:origin/:destination"
echo "    GET  /api/search-history"
echo ""
echo "  Estadísticas:"
echo "    GET  /api/stats"
echo ""
echo ""
echo "📍 DESTINOS CONFIGURADOS"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  ARGENTINA:"
echo "    • AEP - Buenos Aires (Ezeiza) ⭐ PRINCIPAL"
echo "    • COR - Córdoba"
echo ""
echo "  EUROPA (Económicos):"
echo "    • MAD - Madrid, España"
echo "    • BCN - Barcelona, España"
echo "    • LIS - Lisboa, Portugal ⭐ MÁS BARATO"
echo "    • BER - Berlín, Alemania ⭐ MÁS BARATO"
echo "    • FCO - Roma, Italia"
echo ""
echo "  USA (Conexiones directas):"
echo "    • MIA - Miami, Florida ⭐ MEJOR CONEXIÓN"
echo "    • MCO - Orlando, Florida ⭐ MÁS BARATO"
echo "    • JFK - Nueva York"
echo ""
echo ""
echo "⚙️ CONFIGURACIÓN AVANZADA"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  Editar archivo .env:"
echo ""
echo "    PORT=3000                  # Puerto del servidor"
echo "    PRICE_THRESHOLD_EUR=500    # Umbral de precio"
echo "    SCRAPER_TIMEOUT=45000      # Timeout de scraping"
echo "    MAX_RETRIES=2              # Reintentos"
echo ""
echo "  Telegram (opcional):"
echo ""
echo "    TELEGRAM_BOT_TOKEN=xxx     # Token del bot"
echo "    TELEGRAM_CHAT_ID=xxx       # Chat ID"
echo "    ENABLE_CRON=true           # Habilitar búsquedas automáticas"
echo ""
echo ""
echo "❓ PROBLEMAS FRECUENTES"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  Q: Puerto 3000 en uso"
echo "  A: Cambiar PORT en .env"
echo ""
echo "  Q: 'Cannot find module'"
echo "  A: Ejecutar: npm install"
echo ""
echo "  Q: Base de datos corrupta"
echo "  A: rm data/flights.db && npm start (se recrea)"
echo ""
echo "  Q: Puppeteer no descarga"
echo "  A: npm install puppeteer-extra --save-dev"
echo ""
echo ""
echo "📞 SOPORTE"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  Issues: https://github.com/RanuK12/Flight-Price-Alert/issues"
echo "  Docs:   Ver README.md y INSTALL.md"
echo ""
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ ¡Proyecto listo! Ejecuta: npm start"
echo "═══════════════════════════════════════════════════════════════"
echo ""
